version: "3"

services:

  # Traffic SentinelFlask-based Fog API service
  fog_service_1:
    image: ssanchez11/smart_highway_net_fog_service:0.0.1
    container_name: fog-service-1
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Traffic SentinelFlask-based Fog API service
  fog_service_2:
    image: ssanchez11/smart_highway_net_fog_service:0.0.1
    container_name: fog-service-2
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Traffic SentinelFlask-based Fog API service
  fog_service_3:
    image: ssanchez11/smart_highway_net_fog_service:0.0.1
    container_name: fog-service-3
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  fog_service_haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: fog-service-haproxy
    volumes:
      - ./haproxy/fog/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '5000:5000'
      - '1936:1936'
    networks:
      - smart-highway-net

  # Provision service for setting up configurations
  provision_service_1:
    image: ssanchez11/smart_highway_net_provision_service:0.0.1
    container_name: provision-service-1
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Provision service for setting up configurations
  provision_service_2:
    image: ssanchez11/smart_highway_net_provision_service:0.0.1
    container_name: provision-service-2
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Provision service for setting up configurations
  provision_service_3:
    image: ssanchez11/smart_highway_net_provision_service:0.0.1
    container_name: provision-service-3
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  provision_service_haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: provision-service-haproxy
    volumes:
      - ./haproxy/provision/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '5001:5001'
      - '1937:1937'
    networks:
      - smart-highway-net

  # Traffic Sentinel Cameras API service
  cameras_service_1:
    image: ssanchez11/smart_highway_net_cameras_service:0.0.1
    container_name: cameras-service-1
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Traffic Sentinel Cameras API service
  cameras_service_2:
    image: ssanchez11/smart_highway_net_cameras_service:0.0.1
    container_name: cameras-service-2
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Traffic Sentinel Cameras API service
  cameras_service_3:
    image: ssanchez11/smart_highway_net_cameras_service:0.0.1
    container_name: cameras-service-3
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  cameras_service_haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: cameras-service-haproxy
    volumes:
      - ./haproxy/cameras/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '5002:5002'
      - '1938:1938'
    networks:
      - smart-highway-net

  # Traffic Sentinel Users API service
  users_service_1:
    image: ssanchez11/smart_highway_net_users_service:0.0.1
    container_name: users-service-1
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Traffic Sentinel Users API service
  users_service_2:
    image: ssanchez11/smart_highway_net_users_service:0.0.1
    container_name: users-service-2
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Traffic Sentinel Users API service
  users_service_3:
    image: ssanchez11/smart_highway_net_users_service:0.0.1
    container_name: users-service-3
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  users_service_haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: users-service-haproxy
    volumes:
      - ./haproxy/users/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '5003:5003'
      - '1940:1940'
    networks:
      - smart-highway-net

  # Notifier service for sending notifications
  notifier:
    image: ssanchez11/smart_highway_net_notifier_service:0.0.1
    container_name: notifier-service
    env_file:
      - ./.env
    networks:
      - smart-highway-net


  # Traffic Sentinel Stream API service
  stream_service_1:
    image: ssanchez11/smart_highway_net_stream_service:0.0.1
    container_name: stream-service-1
    env_file:
      - ./.env
    networks:
      - smart-highway-net

networks:
  smart-highway-net:
    driver: bridge
