version: "3"

services:

  # Flask-based authentication service for authorization and authentication
  auth_service_1:
    image: ssanchez11/smart_highway_net_auth_service:0.0.1
    container_name: auth-service-1
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Flask-based authentication service for authorization and authentication
  auth_service_2:
    image: ssanchez11/smart_highway_net_auth_service:0.0.1
    container_name: auth-service-2
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Flask-based authentication service for authorization and authentication
  auth_service_3:
    image: ssanchez11/smart_highway_net_auth_service:0.0.1
    container_name: auth-service-3
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  auth_service_haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: auth-service-haproxy
    volumes:
      - ./haproxy/auth/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '5000:5000'
      - '1936:1936'
    networks:
      - smart-highway-net

  # Provision service for setting up configurations
  provision_service_1:
    image: ssanchez11/smart_highway_net_provision_service:0.0.1
    container_name: provision-service-1
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Provision service for setting up configurations
  provision_service_2:
    image: ssanchez11/smart_highway_net_provision_service:0.0.1
    container_name: provision-service-2
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Provision service for setting up configurations
  provision_service_3:
    image: ssanchez11/smart_highway_net_provision_service:0.0.1
    container_name: provision-service-3
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  provision_service_haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: provision-service-haproxy
    volumes:
      - ./haproxy/provision/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '5001:5001'
      - '1937:1937'
    networks:
      - smart-highway-net

  # VisionFrameAPI service
  vision_service_1:
    image: ssanchez11/smart_highway_net_vision_service:0.0.1
    container_name: vision-service-1
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # VisionFrameAPI service
  vision_service_2:
    image: ssanchez11/smart_highway_net_vision_service:0.0.1
    container_name: vision-service-2
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # VisionFrameAPI service
  vision_service_3:
    image: ssanchez11/smart_highway_net_vision_service:0.0.1
    container_name: vision-service-3
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  vision_service_haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: vision-service-haproxy
    volumes:
      - ./haproxy/vision/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '5002:5002'
      - '1938:1938'
    networks:
      - smart-highway-net

  # Notifier service for sending notifications
  notifier:
    image: ssanchez11/smart_highway_net_notifier_service:0.0.1
    container_name: notifier-service
    env_file:
      - ./.env
    networks:
      - smart-highway-net

networks:
  smart-highway-net:
    driver: bridge
