version: "3"

services:

  # Flask-based authentication service for authorization and authentication
  auth_service:
    image: ssanchez11/smart_highway_net_auth_service:0.0.1
    container_name: auth-service
    env_file:
      - ./.env
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    networks:
      - smart-highway-net

  # Notifier service for sending notifications
  notifier:
    image: ssanchez11/smart_highway_net_notifier_service:0.0.1
    container_name: notifier-service
    env_file:
      - ./.env
    networks:
      - smart-highway-net

  # Provision service for setting up configurations
  provision:
    image: ssanchez11/smart_highway_net_provision_service:0.0.1
    container_name: provision-service
    env_file:
      - ./.env
    ports:
      - "5001:5001"  # Map container port 5001 to host port 5001
    networks:
      - smart-highway-net

# Define a custom bridge network for the services to communicate
networks:
  smart-highway-net:
    driver: bridge  # Use the bridge network driver
