version: "3"


services:

  # Flask-based authentication service for authorization and authentication
  auth_service:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    container_name: auth-service-container
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_PORT=${VAULT_PORT}
    ports:
      - "5000:5000"
    links:
      - vault
      - redis
    depends_on:
      - vault
      - redis
    networks:
      - smart-highway-net 


  notifier:
    build:
      context: ./notifier
      dockerfile: Dockerfile
    container_name: notifier-service
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_EXPIRATION_CHANNEL=${REDIS_EXPIRATION_CHANNEL}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_REAUTH_TOPIC=${MQTT_REAUTH_TOPIC}
    links:
      - mosquitto
      - redis
    depends_on:
      - mosquitto
      - redis
    networks:
      - smart-highway-net 

  provision:
    build:
      context: ./provision
      dockerfile: Dockerfile
    container_name: provision-service
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    links:
      - mosquitto
      - redis
    depends_on:
      - mosquitto
      - redis
    networks:
      - smart-highway-net 

  integrator:
    build:
      context: ./integrator
      dockerfile: Dockerfile
    container_name: integrator
    env_file:
      - ./.env
    environment:
      - MQTT_BROKER_USERNAME=${MQTT_BROKER_USERNAME}
      - MQTT_BROKER_PASSWORD=${MQTT_BROKER_PASSWORD}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    depends_on:
      - zookeeper
      - kafka
      - mosquitto
    links:
      - zookeeper
      - kafka
      - mosquitto
    networks:
      - smart-highway-net 

networks:
  smart-highway-net:
    driver: bridge
