version: "3"

services:

  # Flask-based authentication service for authorization and authentication
  auth_service:
    image: ssanchez11/smart_highway_net_auth_service:0.0.1
    container_name: auth-service
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
    ports:
      - "5000:5000"
    networks:
      - smart-highway-net

  notifier:
    image: ssanchez11/smart_highway_net_notifier_service:0.0.1
    container_name: notifier-service
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_EXPIRATION_CHANNEL=${REDIS_EXPIRATION_CHANNEL}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_REAUTH_TOPIC=${MQTT_REAUTH_TOPIC}
    networks:
      - smart-highway-net

  provision:
    image: ssanchez11/smart_highway_net_provision_service:0.0.1
    container_name: provision-service
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    networks:
      - smart-highway-net

  integrator:
    image: ssanchez11/smart_highway_net_integrator_service:0.0.1
    container_name: integrator-service
    env_file:
      - ./.env
    environment:
      - MQTT_BROKER_USERNAME=${MQTT_BROKER_USERNAME}
      - MQTT_BROKER_PASSWORD=${MQTT_BROKER_PASSWORD}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    networks:
      - smart-highway-net

networks:
  smart-highway-net:
    driver: bridge
