version: "3"

services:

  # Flink Job Manager service for distributed processing
  jobmanager:
    image: ssanchez11/smart_highway_net_job_manager_flink:0.0.1
    container_name: job-manager-flink
    volumes:
      - ./jobs:/opt/flink/jobs  # Map local jobs directory to the container
    ports:
      - "8085:8081"  # Map container port 8081 to host port 8085
    command: jobmanager  # Run the job manager
    env_file:
      - ./.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - smart-highway-net

  # Flink Task Manager service for distributed processing
  taskmanager:
    image: ssanchez11/smart_highway_net_task_manager_flink:0.0.1
    container_name: task-manager-flink
    volumes:
      - ./jobs:/opt/flink/jobs  # Map local jobs directory to the container
    depends_on:
      - jobmanager  # Ensure that the job manager is ready before starting the task manager
    command: taskmanager  # Run the task manager
    scale: 1  # Scale to 1 instance
    env_file:
      - ./.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - smart-highway-net

# Define a custom bridge network for the services to communicate
networks:
  smart-highway-net:
    driver: bridge  # Use the bridge network driver
