version: "3"

services:

  # Flink Job Manager service for distributed processing
  jobmanager:
    image: ssanchez11/smart_highway_net_job_manager_flink:0.0.1
    container_name: job-manager-flink
    volumes:
      - ./jobs:/opt/flink/jobs
    ports:
      - "8085:8081"
    command: jobmanager
    env_file:
      - ./.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - smart-highway-net

  # Flink Task Manager service for distributed processing
  taskmanager_1:
    image: ssanchez11/smart_highway_net_task_manager_flink:0.0.1
    container_name: task-manager-flink-1
    volumes:
      - ./jobs:/opt/flink/jobs
    depends_on:
      - jobmanager
    command: taskmanager 
    env_file:
      - ./.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - smart-highway-net

  #Flink Task Manager service for distributed processing
  taskmanager_2:
    image: ssanchez11/smart_highway_net_task_manager_flink:0.0.1
    container_name: task-manager-flink-2
    volumes:
      - ./jobs:/opt/flink/jobs
    depends_on:
      - jobmanager
    command: taskmanager 
    env_file:
      - ./.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - smart-highway-net

networks:
  smart-highway-net:
    driver: bridge
