# Docker Compose Configuration for Fog Node Service

version: '3'  # Specifies the Docker Compose version being used.

services:

  # Fog Node Service Configuration
  fog_node_1:
    image: ssanchez11/smart_highway_net_fog_node:0.0.1
    container_name: fog_node_1
    env_file:
      - ./.env  # Specifies the environment file to use for this service.
    mac_address: "02:42:ac:11:00:02"  # Specifies the MAC address for the container, useful in network configurations.
