# Docker Compose Configuration for Fog Node Service

version: '3'

services:

  # Fog Node Service Configuration
  fog_node_1:
    image: ssanchez11/smart_highway_net_fog_node:0.0.1
    container_name: fog_node_1
    env_file:
      - ./.env
    mac_address: "02:42:ac:11:00:02"

  # Fog Node Service Configuration
  fog_node_2:
    image: ssanchez11/smart_highway_net_fog_node:0.0.1
    container_name: fog_node_2
    env_file:
      - ./.env
    mac_address: "23:54:ac:43:12:03"

  # Fog Node Service Configuration
  fog_node_3:
    image: ssanchez11/smart_highway_net_fog_node:0.0.1
    container_name: fog_node_3
    env_file:
      - ./.env
    mac_address: "15:23:56:34:12:03"
