version: "3"

services:

  # Manage & view data inside your Apache Kafka ® cluster
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "192.168.1.39:29092"
    ports:
      - 8088:8080
    networks:
      - smart-highway-net 

networks:
  smart-highway-net:
    driver: bridge  # Use the bridge network driver
